### ISSUE TITLE
[express-apollo-prisma] Queueing: Add Worker/Job processor + setup

### ISSUE THREAD

**Issue by ihardz** [thisdot/starter.dev#1084]
**Description:**
* Select queue tech. Such as ElasticMQ, RabbitMQ, etc.
* Infrastructure Setup: Add setup to the docker compose with setup instructions
* Add a worker that can process the job added to the queue. It should simply print the job message to STDOUT.

**Acceptance Criteria:**

* docker container created with script
* Message brocker hosted in docker container
* Worker/Job processor implemntation (Receive)
* Have a script that starts Worker

configuration (clarification here: https://x-team.com/blog/set-up-rabbitmq-with-docker-compose/): 
```
<...>
services:
<...>
  rabbitmq:
    image: rabbitmq:3.11.9-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
```

Helpful Docs:
* Image/Container specification: https://hub.docker.com/_/rabbitmq
* RabbitMQ docs: https://www.rabbitmq.com/tutorials/tutorial-one-javascript.html
* Worker sample: https://medium.com/@otavioguastamacchia/implementing-worker-applications-with-rabbitmq-node-1a8b7ab98e47
