### ISSUE TITLE
[express-apollo-prisma] kit causes "system-wide" side-effect

### ISSUE THREAD

**Issue by mbicknese** [thisdot/starter.dev#1142]
Our [`docker-compose.yaml`](https://github.com/thisdot/starter.dev/blob/bd203573cf976afa12dec56b560ae88fa6d6bcdf/starters/express-apollo-prisma/docker-compose.yaml) writes files to the local user's user directory. 

```yaml
  rabbitmq:
    // ...
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
```

Users of the kit might/will only expect the project to write within its project directory. Removing the folder now leaves clutter on the system. We should contain our files in the project directory.
Additionally, other projects could collide with this kit when both write their MQ persistence to the same place. This is a minor issue as the location doesn't seem to be a common convention.

One of the possible solutions to this is to create docker volumes for persistence for RabbitMQ. 

## Acceptance criteria

 1. Kit doesn't write outside its project directory on usage
